# MongoDB example:
# spring.data.mongodb.uri=mongodb://localhost:27017/blogdb
spring.application.name=blog 
server.port=8080 
spring.data.mongodb.uri=mongodb://localhost:27017/blogdb 
spring.data.mongodb.auto-index-creation=true